//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Mvc4_Kulti
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class AgenciesEntities : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues AgenciesEntities-Objekt mithilfe der in Abschnitt 'AgenciesEntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public AgenciesEntities() : base("name=AgenciesEntities", "AgenciesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues AgenciesEntities-Objekt.
        /// </summary>
        public AgenciesEntities(string connectionString) : base(connectionString, "AgenciesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues AgenciesEntities-Objekt.
        /// </summary>
        public AgenciesEntities(EntityConnection connection) : base(connection, "AgenciesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Agencies> Agencies
        {
            get
            {
                if ((_Agencies == null))
                {
                    _Agencies = base.CreateObjectSet<Agencies>("Agencies");
                }
                return _Agencies;
            }
        }
        private ObjectSet<Agencies> _Agencies;

        #endregion

        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Agencies'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToAgencies(Agencies agencies)
        {
            base.AddObject("Agencies", agencies);
        }

        #endregion

    }

    #endregion

    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgencyModel", Name="Agencies")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Agencies : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Agencies-Objekt.
        /// </summary>
        /// <param name="agencyId">Anfangswert der Eigenschaft AgencyId.</param>
        public static Agencies CreateAgencies(global::System.Int32 agencyId)
        {
            Agencies agencies = new Agencies();
            agencies.AgencyId = agencyId;
            return agencies;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AgencyId
        {
            get
            {
                return _AgencyId;
            }
            set
            {
                if (_AgencyId != value)
                {
                    OnAgencyIdChanging(value);
                    ReportPropertyChanging("AgencyId");
                    _AgencyId = StructuralObject.SetValidValue(value, "AgencyId");
                    ReportPropertyChanged("AgencyId");
                    OnAgencyIdChanged();
                }
            }
        }
        private global::System.Int32 _AgencyId;
        partial void OnAgencyIdChanging(global::System.Int32 value);
        partial void OnAgencyIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AgenyGroupId
        {
            get
            {
                return _AgenyGroupId;
            }
            set
            {
                OnAgenyGroupIdChanging(value);
                ReportPropertyChanging("AgenyGroupId");
                _AgenyGroupId = StructuralObject.SetValidValue(value, "AgenyGroupId");
                ReportPropertyChanged("AgenyGroupId");
                OnAgenyGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AgenyGroupId;
        partial void OnAgenyGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnAgenyGroupIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyName
        {
            get
            {
                return _AgencyName;
            }
            set
            {
                OnAgencyNameChanging(value);
                ReportPropertyChanging("AgencyName");
                _AgencyName = StructuralObject.SetValidValue(value, true, "AgencyName");
                ReportPropertyChanged("AgencyName");
                OnAgencyNameChanged();
            }
        }
        private global::System.String _AgencyName;
        partial void OnAgencyNameChanging(global::System.String value);
        partial void OnAgencyNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyEmail
        {
            get
            {
                return _AgencyEmail;
            }
            set
            {
                OnAgencyEmailChanging(value);
                ReportPropertyChanging("AgencyEmail");
                _AgencyEmail = StructuralObject.SetValidValue(value, true, "AgencyEmail");
                ReportPropertyChanged("AgencyEmail");
                OnAgencyEmailChanged();
            }
        }
        private global::System.String _AgencyEmail;
        partial void OnAgencyEmailChanging(global::System.String value);
        partial void OnAgencyEmailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyPhone
        {
            get
            {
                return _AgencyPhone;
            }
            set
            {
                OnAgencyPhoneChanging(value);
                ReportPropertyChanging("AgencyPhone");
                _AgencyPhone = StructuralObject.SetValidValue(value, true, "AgencyPhone");
                ReportPropertyChanged("AgencyPhone");
                OnAgencyPhoneChanged();
            }
        }
        private global::System.String _AgencyPhone;
        partial void OnAgencyPhoneChanging(global::System.String value);
        partial void OnAgencyPhoneChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyStreet
        {
            get
            {
                return _AgencyStreet;
            }
            set
            {
                OnAgencyStreetChanging(value);
                ReportPropertyChanging("AgencyStreet");
                _AgencyStreet = StructuralObject.SetValidValue(value, true, "AgencyStreet");
                ReportPropertyChanged("AgencyStreet");
                OnAgencyStreetChanged();
            }
        }
        private global::System.String _AgencyStreet;
        partial void OnAgencyStreetChanging(global::System.String value);
        partial void OnAgencyStreetChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyZip
        {
            get
            {
                return _AgencyZip;
            }
            set
            {
                OnAgencyZipChanging(value);
                ReportPropertyChanging("AgencyZip");
                _AgencyZip = StructuralObject.SetValidValue(value, true, "AgencyZip");
                ReportPropertyChanged("AgencyZip");
                OnAgencyZipChanged();
            }
        }
        private global::System.String _AgencyZip;
        partial void OnAgencyZipChanging(global::System.String value);
        partial void OnAgencyZipChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgencyCity
        {
            get
            {
                return _AgencyCity;
            }
            set
            {
                OnAgencyCityChanging(value);
                ReportPropertyChanging("AgencyCity");
                _AgencyCity = StructuralObject.SetValidValue(value, true, "AgencyCity");
                ReportPropertyChanged("AgencyCity");
                OnAgencyCityChanged();
            }
        }
        private global::System.String _AgencyCity;
        partial void OnAgencyCityChanging(global::System.String value);
        partial void OnAgencyCityChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactFirstName
        {
            get
            {
                return _ContactFirstName;
            }
            set
            {
                OnContactFirstNameChanging(value);
                ReportPropertyChanging("ContactFirstName");
                _ContactFirstName = StructuralObject.SetValidValue(value, true, "ContactFirstName");
                ReportPropertyChanged("ContactFirstName");
                OnContactFirstNameChanged();
            }
        }
        private global::System.String _ContactFirstName;
        partial void OnContactFirstNameChanging(global::System.String value);
        partial void OnContactFirstNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactLastName
        {
            get
            {
                return _ContactLastName;
            }
            set
            {
                OnContactLastNameChanging(value);
                ReportPropertyChanging("ContactLastName");
                _ContactLastName = StructuralObject.SetValidValue(value, true, "ContactLastName");
                ReportPropertyChanged("ContactLastName");
                OnContactLastNameChanged();
            }
        }
        private global::System.String _ContactLastName;
        partial void OnContactLastNameChanging(global::System.String value);
        partial void OnContactLastNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactEmail
        {
            get
            {
                return _ContactEmail;
            }
            set
            {
                OnContactEmailChanging(value);
                ReportPropertyChanging("ContactEmail");
                _ContactEmail = StructuralObject.SetValidValue(value, true, "ContactEmail");
                ReportPropertyChanged("ContactEmail");
                OnContactEmailChanged();
            }
        }
        private global::System.String _ContactEmail;
        partial void OnContactEmailChanging(global::System.String value);
        partial void OnContactEmailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhone
        {
            get
            {
                return _ContactPhone;
            }
            set
            {
                OnContactPhoneChanging(value);
                ReportPropertyChanging("ContactPhone");
                _ContactPhone = StructuralObject.SetValidValue(value, true, "ContactPhone");
                ReportPropertyChanged("ContactPhone");
                OnContactPhoneChanged();
            }
        }
        private global::System.String _ContactPhone;
        partial void OnContactPhoneChanging(global::System.String value);
        partial void OnContactPhoneChanged();

        #endregion

    }

    #endregion

}
