//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Mvc4_Kulti
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class ExternalUsersEntities : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues ExternalUsersEntities-Objekt mithilfe der in Abschnitt 'ExternalUsersEntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public ExternalUsersEntities() : base("name=ExternalUsersEntities", "ExternalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues ExternalUsersEntities-Objekt.
        /// </summary>
        public ExternalUsersEntities(string connectionString) : base(connectionString, "ExternalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues ExternalUsersEntities-Objekt.
        /// </summary>
        public ExternalUsersEntities(EntityConnection connection) : base(connection, "ExternalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<ExternalUsers> ExternalUsers
        {
            get
            {
                if ((_ExternalUsers == null))
                {
                    _ExternalUsers = base.CreateObjectSet<ExternalUsers>("ExternalUsers");
                }
                return _ExternalUsers;
            }
        }
        private ObjectSet<ExternalUsers> _ExternalUsers;

        #endregion

        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'ExternalUsers'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToExternalUsers(ExternalUsers externalUsers)
        {
            base.AddObject("ExternalUsers", externalUsers);
        }

        #endregion

    }

    #endregion

    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExternalUsersModel", Name="ExternalUsers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExternalUsers : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues ExternalUsers-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        public static ExternalUsers CreateExternalUsers(global::System.Int32 id)
        {
            ExternalUsers externalUsers = new ExternalUsers();
            externalUsers.ID = id;
            return externalUsers;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email2
        {
            get
            {
                return _Email2;
            }
            set
            {
                OnEmail2Changing(value);
                ReportPropertyChanging("Email2");
                _Email2 = StructuralObject.SetValidValue(value, true, "Email2");
                ReportPropertyChanged("Email2");
                OnEmail2Changed();
            }
        }
        private global::System.String _Email2;
        partial void OnEmail2Changing(global::System.String value);
        partial void OnEmail2Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mieter
        {
            get
            {
                return _Mieter;
            }
            set
            {
                OnMieterChanging(value);
                ReportPropertyChanging("Mieter");
                _Mieter = StructuralObject.SetValidValue(value, true, "Mieter");
                ReportPropertyChanged("Mieter");
                OnMieterChanged();
            }
        }
        private global::System.String _Mieter;
        partial void OnMieterChanging(global::System.String value);
        partial void OnMieterChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bewohner
        {
            get
            {
                return _Bewohner;
            }
            set
            {
                OnBewohnerChanging(value);
                ReportPropertyChanging("Bewohner");
                _Bewohner = StructuralObject.SetValidValue(value, true, "Bewohner");
                ReportPropertyChanged("Bewohner");
                OnBewohnerChanged();
            }
        }
        private global::System.String _Bewohner;
        partial void OnBewohnerChanging(global::System.String value);
        partial void OnBewohnerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Beiz
        {
            get
            {
                return _Beiz;
            }
            set
            {
                OnBeizChanging(value);
                ReportPropertyChanging("Beiz");
                _Beiz = StructuralObject.SetValidValue(value, true, "Beiz");
                ReportPropertyChanged("Beiz");
                OnBeizChanged();
            }
        }
        private global::System.String _Beiz;
        partial void OnBeizChanging(global::System.String value);
        partial void OnBeizChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KoKo
        {
            get
            {
                return _KoKo;
            }
            set
            {
                OnKoKoChanging(value);
                ReportPropertyChanging("KoKo");
                _KoKo = StructuralObject.SetValidValue(value, true, "KoKo");
                ReportPropertyChanged("KoKo");
                OnKoKoChanged();
            }
        }
        private global::System.String _KoKo;
        partial void OnKoKoChanging(global::System.String value);
        partial void OnKoKoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Halle
        {
            get
            {
                return _Halle;
            }
            set
            {
                OnHalleChanging(value);
                ReportPropertyChanging("Halle");
                _Halle = StructuralObject.SetValidValue(value, true, "Halle");
                ReportPropertyChanged("Halle");
                OnHalleChanged();
            }
        }
        private global::System.String _Halle;
        partial void OnHalleChanging(global::System.String value);
        partial void OnHalleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gewerbetrakt
        {
            get
            {
                return _Gewerbetrakt;
            }
            set
            {
                OnGewerbetraktChanging(value);
                ReportPropertyChanging("Gewerbetrakt");
                _Gewerbetrakt = StructuralObject.SetValidValue(value, true, "Gewerbetrakt");
                ReportPropertyChanged("Gewerbetrakt");
                OnGewerbetraktChanged();
            }
        }
        private global::System.String _Gewerbetrakt;
        partial void OnGewerbetraktChanging(global::System.String value);
        partial void OnGewerbetraktChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Giesserei
        {
            get
            {
                return _Giesserei;
            }
            set
            {
                OnGiessereiChanging(value);
                ReportPropertyChanging("Giesserei");
                _Giesserei = StructuralObject.SetValidValue(value, true, "Giesserei");
                ReportPropertyChanged("Giesserei");
                OnGiessereiChanged();
            }
        }
        private global::System.String _Giesserei;
        partial void OnGiessereiChanging(global::System.String value);
        partial void OnGiessereiChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Schuer
        {
            get
            {
                return _Schuer;
            }
            set
            {
                OnSchuerChanging(value);
                ReportPropertyChanging("Schuer");
                _Schuer = StructuralObject.SetValidValue(value, true, "Schuer");
                ReportPropertyChanged("Schuer");
                OnSchuerChanged();
            }
        }
        private global::System.String _Schuer;
        partial void OnSchuerChanging(global::System.String value);
        partial void OnSchuerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Villa
        {
            get
            {
                return _Villa;
            }
            set
            {
                OnVillaChanging(value);
                ReportPropertyChanging("Villa");
                _Villa = StructuralObject.SetValidValue(value, true, "Villa");
                ReportPropertyChanged("Villa");
                OnVillaChanged();
            }
        }
        private global::System.String _Villa;
        partial void OnVillaChanging(global::System.String value);
        partial void OnVillaChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Wagenstrasse
        {
            get
            {
                return _Wagenstrasse;
            }
            set
            {
                OnWagenstrasseChanging(value);
                ReportPropertyChanging("Wagenstrasse");
                _Wagenstrasse = StructuralObject.SetValidValue(value, true, "Wagenstrasse");
                ReportPropertyChanged("Wagenstrasse");
                OnWagenstrasseChanged();
            }
        }
        private global::System.String _Wagenstrasse;
        partial void OnWagenstrasseChanging(global::System.String value);
        partial void OnWagenstrasseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Veranstalter
        {
            get
            {
                return _Veranstalter;
            }
            set
            {
                OnVeranstalterChanging(value);
                ReportPropertyChanging("Veranstalter");
                _Veranstalter = StructuralObject.SetValidValue(value, true, "Veranstalter");
                ReportPropertyChanged("Veranstalter");
                OnVeranstalterChanged();
            }
        }
        private global::System.String _Veranstalter;
        partial void OnVeranstalterChanging(global::System.String value);
        partial void OnVeranstalterChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Geschaeftlich
        {
            get
            {
                return _Geschaeftlich;
            }
            set
            {
                OnGeschaeftlichChanging(value);
                ReportPropertyChanging("Geschaeftlich");
                _Geschaeftlich = StructuralObject.SetValidValue(value, true, "Geschaeftlich");
                ReportPropertyChanged("Geschaeftlich");
                OnGeschaeftlichChanged();
            }
        }
        private global::System.String _Geschaeftlich;
        partial void OnGeschaeftlichChanging(global::System.String value);
        partial void OnGeschaeftlichChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Verwaltung
        {
            get
            {
                return _Verwaltung;
            }
            set
            {
                OnVerwaltungChanging(value);
                ReportPropertyChanging("Verwaltung");
                _Verwaltung = StructuralObject.SetValidValue(value, true, "Verwaltung");
                ReportPropertyChanged("Verwaltung");
                OnVerwaltungChanged();
            }
        }
        private global::System.String _Verwaltung;
        partial void OnVerwaltungChanging(global::System.String value);
        partial void OnVerwaltungChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stiftung
        {
            get
            {
                return _Stiftung;
            }
            set
            {
                OnStiftungChanging(value);
                ReportPropertyChanging("Stiftung");
                _Stiftung = StructuralObject.SetValidValue(value, true, "Stiftung");
                ReportPropertyChanged("Stiftung");
                OnStiftungChanged();
            }
        }
        private global::System.String _Stiftung;
        partial void OnStiftungChanging(global::System.String value);
        partial void OnStiftungChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prot_Traeve
        {
            get
            {
                return _Prot_Traeve;
            }
            set
            {
                OnProt_TraeveChanging(value);
                ReportPropertyChanging("Prot_Traeve");
                _Prot_Traeve = StructuralObject.SetValidValue(value, true, "Prot_Traeve");
                ReportPropertyChanged("Prot_Traeve");
                OnProt_TraeveChanged();
            }
        }
        private global::System.String _Prot_Traeve;
        partial void OnProt_TraeveChanging(global::System.String value);
        partial void OnProt_TraeveChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prot_Koko
        {
            get
            {
                return _Prot_Koko;
            }
            set
            {
                OnProt_KokoChanging(value);
                ReportPropertyChanging("Prot_Koko");
                _Prot_Koko = StructuralObject.SetValidValue(value, true, "Prot_Koko");
                ReportPropertyChanged("Prot_Koko");
                OnProt_KokoChanged();
            }
        }
        private global::System.String _Prot_Koko;
        partial void OnProt_KokoChanging(global::System.String value);
        partial void OnProt_KokoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prot_Halle
        {
            get
            {
                return _Prot_Halle;
            }
            set
            {
                OnProt_HalleChanging(value);
                ReportPropertyChanging("Prot_Halle");
                _Prot_Halle = StructuralObject.SetValidValue(value, true, "Prot_Halle");
                ReportPropertyChanged("Prot_Halle");
                OnProt_HalleChanged();
            }
        }
        private global::System.String _Prot_Halle;
        partial void OnProt_HalleChanging(global::System.String value);
        partial void OnProt_HalleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prot_Beiz
        {
            get
            {
                return _Prot_Beiz;
            }
            set
            {
                OnProt_BeizChanging(value);
                ReportPropertyChanging("Prot_Beiz");
                _Prot_Beiz = StructuralObject.SetValidValue(value, true, "Prot_Beiz");
                ReportPropertyChanged("Prot_Beiz");
                OnProt_BeizChanged();
            }
        }
        private global::System.String _Prot_Beiz;
        partial void OnProt_BeizChanging(global::System.String value);
        partial void OnProt_BeizChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ehemalige
        {
            get
            {
                return _Ehemalige;
            }
            set
            {
                OnEhemaligeChanging(value);
                ReportPropertyChanging("Ehemalige");
                _Ehemalige = StructuralObject.SetValidValue(value, true, "Ehemalige");
                ReportPropertyChanged("Ehemalige");
                OnEhemaligeChanged();
            }
        }
        private global::System.String _Ehemalige;
        partial void OnEhemaligeChanging(global::System.String value);
        partial void OnEhemaligeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sonstige
        {
            get
            {
                return _Sonstige;
            }
            set
            {
                OnSonstigeChanging(value);
                ReportPropertyChanging("Sonstige");
                _Sonstige = StructuralObject.SetValidValue(value, true, "Sonstige");
                ReportPropertyChanged("Sonstige");
                OnSonstigeChanged();
            }
        }
        private global::System.String _Sonstige;
        partial void OnSonstigeChanging(global::System.String value);
        partial void OnSonstigeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion

    }

    #endregion

}
