//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Mvc4_Kulti
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class KultiEventsModel : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues KultiEventsModel-Objekt mithilfe der in Abschnitt 'KultiEventsModel' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public KultiEventsModel() : base("name=KultiEventsModel", "KultiEventsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues KultiEventsModel-Objekt.
        /// </summary>
        public KultiEventsModel(string connectionString) : base(connectionString, "KultiEventsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues KultiEventsModel-Objekt.
        /// </summary>
        public KultiEventsModel(EntityConnection connection) : base(connection, "KultiEventsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Events> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Events>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Events> _Events;

        #endregion

        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Events'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToEvents(Events events)
        {
            base.AddObject("Events", events);
        }

        #endregion

    }

    #endregion

    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KultiEventModel", Name="Events")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Events : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Events-Objekt.
        /// </summary>
        /// <param name="eventId">Anfangswert der Eigenschaft EventId.</param>
        public static Events CreateEvents(global::System.Int32 eventId)
        {
            Events events = new Events();
            events.EventId = eventId;
            return events;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                if (_EventId != value)
                {
                    OnEventIdChanging(value);
                    ReportPropertyChanging("EventId");
                    _EventId = StructuralObject.SetValidValue(value, "EventId");
                    ReportPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvTitle
        {
            get
            {
                return _EvTitle;
            }
            set
            {
                OnEvTitleChanging(value);
                ReportPropertyChanging("EvTitle");
                _EvTitle = StructuralObject.SetValidValue(value, true, "EvTitle");
                ReportPropertyChanged("EvTitle");
                OnEvTitleChanged();
            }
        }
        private global::System.String _EvTitle;
        partial void OnEvTitleChanging(global::System.String value);
        partial void OnEvTitleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EvStartDate
        {
            get
            {
                return _EvStartDate;
            }
            set
            {
                OnEvStartDateChanging(value);
                ReportPropertyChanging("EvStartDate");
                _EvStartDate = StructuralObject.SetValidValue(value, "EvStartDate");
                ReportPropertyChanged("EvStartDate");
                OnEvStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EvStartDate;
        partial void OnEvStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEvStartDateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EvEndDate
        {
            get
            {
                return _EvEndDate;
            }
            set
            {
                OnEvEndDateChanging(value);
                ReportPropertyChanging("EvEndDate");
                _EvEndDate = StructuralObject.SetValidValue(value, "EvEndDate");
                ReportPropertyChanged("EvEndDate");
                OnEvEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EvEndDate;
        partial void OnEvEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEvEndDateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvUserId
        {
            get
            {
                return _EvUserId;
            }
            set
            {
                OnEvUserIdChanging(value);
                ReportPropertyChanging("EvUserId");
                _EvUserId = StructuralObject.SetValidValue(value, "EvUserId");
                ReportPropertyChanged("EvUserId");
                OnEvUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EvUserId;
        partial void OnEvUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnEvUserIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvImgPath1
        {
            get
            {
                return _EvImgPath1;
            }
            set
            {
                OnEvImgPath1Changing(value);
                ReportPropertyChanging("EvImgPath1");
                _EvImgPath1 = StructuralObject.SetValidValue(value, true, "EvImgPath1");
                ReportPropertyChanged("EvImgPath1");
                OnEvImgPath1Changed();
            }
        }
        private global::System.String _EvImgPath1;
        partial void OnEvImgPath1Changing(global::System.String value);
        partial void OnEvImgPath1Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvImgPath2
        {
            get
            {
                return _EvImgPath2;
            }
            set
            {
                OnEvImgPath2Changing(value);
                ReportPropertyChanging("EvImgPath2");
                _EvImgPath2 = StructuralObject.SetValidValue(value, true, "EvImgPath2");
                ReportPropertyChanged("EvImgPath2");
                OnEvImgPath2Changed();
            }
        }
        private global::System.String _EvImgPath2;
        partial void OnEvImgPath2Changing(global::System.String value);
        partial void OnEvImgPath2Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvLocation
        {
            get
            {
                return _EvLocation;
            }
            set
            {
                OnEvLocationChanging(value);
                ReportPropertyChanging("EvLocation");
                _EvLocation = StructuralObject.SetValidValue(value, "EvLocation");
                ReportPropertyChanged("EvLocation");
                OnEvLocationChanged();
            }
        }
        private Nullable<global::System.Int32> _EvLocation;
        partial void OnEvLocationChanging(Nullable<global::System.Int32> value);
        partial void OnEvLocationChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvStatus
        {
            get
            {
                return _EvStatus;
            }
            set
            {
                OnEvStatusChanging(value);
                ReportPropertyChanging("EvStatus");
                _EvStatus = StructuralObject.SetValidValue(value, "EvStatus");
                ReportPropertyChanged("EvStatus");
                OnEvStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _EvStatus;
        partial void OnEvStatusChanging(Nullable<global::System.Int32> value);
        partial void OnEvStatusChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvText
        {
            get
            {
                return _EvText;
            }
            set
            {
                OnEvTextChanging(value);
                ReportPropertyChanging("EvText");
                _EvText = StructuralObject.SetValidValue(value, true, "EvText");
                ReportPropertyChanged("EvText");
                OnEvTextChanged();
            }
        }
        private global::System.String _EvText;
        partial void OnEvTextChanging(global::System.String value);
        partial void OnEvTextChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvAdmission
        {
            get
            {
                return _EvAdmission;
            }
            set
            {
                OnEvAdmissionChanging(value);
                ReportPropertyChanging("EvAdmission");
                _EvAdmission = StructuralObject.SetValidValue(value, true, "EvAdmission");
                ReportPropertyChanged("EvAdmission");
                OnEvAdmissionChanged();
            }
        }
        private global::System.String _EvAdmission;
        partial void OnEvAdmissionChanging(global::System.String value);
        partial void OnEvAdmissionChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvType
        {
            get
            {
                return _EvType;
            }
            set
            {
                OnEvTypeChanging(value);
                ReportPropertyChanging("EvType");
                _EvType = StructuralObject.SetValidValue(value, "EvType");
                ReportPropertyChanged("EvType");
                OnEvTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EvType;
        partial void OnEvTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEvTypeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvGroupId
        {
            get
            {
                return _EvGroupId;
            }
            set
            {
                OnEvGroupIdChanging(value);
                ReportPropertyChanging("EvGroupId");
                _EvGroupId = StructuralObject.SetValidValue(value, "EvGroupId");
                ReportPropertyChanged("EvGroupId");
                OnEvGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EvGroupId;
        partial void OnEvGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnEvGroupIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvResponsible
        {
            get
            {
                return _EvResponsible;
            }
            set
            {
                OnEvResponsibleChanging(value);
                ReportPropertyChanging("EvResponsible");
                _EvResponsible = StructuralObject.SetValidValue(value, true, "EvResponsible");
                ReportPropertyChanged("EvResponsible");
                OnEvResponsibleChanged();
            }
        }
        private global::System.String _EvResponsible;
        partial void OnEvResponsibleChanging(global::System.String value);
        partial void OnEvResponsibleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvAgencyId
        {
            get
            {
                return _EvAgencyId;
            }
            set
            {
                OnEvAgencyIdChanging(value);
                ReportPropertyChanging("EvAgencyId");
                _EvAgencyId = StructuralObject.SetValidValue(value, "EvAgencyId");
                ReportPropertyChanged("EvAgencyId");
                OnEvAgencyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EvAgencyId;
        partial void OnEvAgencyIdChanging(Nullable<global::System.Int32> value);
        partial void OnEvAgencyIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EvInterInfo
        {
            get
            {
                return _EvInterInfo;
            }
            set
            {
                OnEvInterInfoChanging(value);
                ReportPropertyChanging("EvInterInfo");
                _EvInterInfo = StructuralObject.SetValidValue(value, true, "EvInterInfo");
                ReportPropertyChanged("EvInterInfo");
                OnEvInterInfoChanged();
            }
        }
        private global::System.String _EvInterInfo;
        partial void OnEvInterInfoChanging(global::System.String value);
        partial void OnEvInterInfoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EvSize
        {
            get
            {
                return _EvSize;
            }
            set
            {
                OnEvSizeChanging(value);
                ReportPropertyChanging("EvSize");
                _EvSize = StructuralObject.SetValidValue(value, "EvSize");
                ReportPropertyChanged("EvSize");
                OnEvSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _EvSize;
        partial void OnEvSizeChanging(Nullable<global::System.Int32> value);
        partial void OnEvSizeChanged();

        #endregion

    }

    #endregion

}
